### ISSUE TITLE
Starting SIE DNS sensor nmsgtool error

### ISSUE THREAD

**Issue by mikeydiamonds** [farsightsec/sie-dns-sensor#7]
I'm experimenting with putting the SIE DNS sensor in a docker container. The container just constantly restarts and I'm not sure what the issue is.
I have a simple Dockerfile:
```
FROM ubuntu:18.04

ENV SRC_HOME=/etc/farsight

WORKDIR $SRC_HOME

RUN apt-get update && apt-get -y upgrade && apt-get install -y libpcap0.8 openssh-client

ADD https://github.com/farsightsec/sie-dns-sensor/raw/master/binaries/0.11.2-1/sie-dns-sensor_0.11.2-1_amd64.deb $SRC_HOME
RUN dpkg -i sie-dns-sensor_0.11.2-1_amd64.deb

EXPOSE 49222
```
I use ansible to provision the server. I've mounted a volume to get sie-dns-sensor config and the keys into the container. This error message just repeats: `Starting SIE DNS sensor nmsgtool`. Maybe you can point me in the direction of a fix? Thanks!

**Comment by mikeydiamonds** [comment]
I figured it out. I needed an entry point and added `CMD service sie-dns-sensor start` to the dockerfile. Also, the `EXPOSE 49222` is not needed.

**Comment by vixie** [comment]
can you share  your completed dockerfile?

**Comment by mikeydiamonds** [comment]
sure @vixie 
```
# Install Farsight Security Sensor

FROM ubuntu:18.04

ENV SRC_HOME=/etc/farsight-src

WORKDIR $SRC_HOME

RUN apt-get update && apt-get -y upgrade && apt-get install -y libpcap0.8 openssh-client

ADD https://github.com/farsightsec/sie-dns-sensor/raw/master/binaries/0.11.2-1/sie-dns-sensor_0.11.2-1_amd64.deb $SRC_HOME
RUN dpkg -i sie-dns-sensor_0.11.2-1_amd64.deb

CMD service sie-dns-sensor start && tail -F /var/log/bootstrap.log```
